package com.javaee.hotel.domain;

public class CustomerInfo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer_info.id
     *
     * @mbg.generated Mon Jul 22 16:39:23 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer_info.telephone
     *
     * @mbg.generated Mon Jul 22 16:39:23 CST 2019
     */
    private String telephone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer_info.email
     *
     * @mbg.generated Mon Jul 22 16:39:23 CST 2019
     */
    private String email;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer_info.nick_name
     *
     * @mbg.generated Mon Jul 22 16:39:23 CST 2019
     */
    private String nickName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer_info.icon
     *
     * @mbg.generated Mon Jul 22 16:39:23 CST 2019
     */
    private String icon;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer_info.id
     *
     * @return the value of customer_info.id
     *
     * @mbg.generated Mon Jul 22 16:39:23 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer_info.id
     *
     * @param id the value for customer_info.id
     *
     * @mbg.generated Mon Jul 22 16:39:23 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer_info.telephone
     *
     * @return the value of customer_info.telephone
     *
     * @mbg.generated Mon Jul 22 16:39:23 CST 2019
     */
    public String getTelephone() {
        return telephone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer_info.telephone
     *
     * @param telephone the value for customer_info.telephone
     *
     * @mbg.generated Mon Jul 22 16:39:23 CST 2019
     */
    public void setTelephone(String telephone) {
        this.telephone = telephone == null ? null : telephone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer_info.email
     *
     * @return the value of customer_info.email
     *
     * @mbg.generated Mon Jul 22 16:39:23 CST 2019
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer_info.email
     *
     * @param email the value for customer_info.email
     *
     * @mbg.generated Mon Jul 22 16:39:23 CST 2019
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer_info.nick_name
     *
     * @return the value of customer_info.nick_name
     *
     * @mbg.generated Mon Jul 22 16:39:23 CST 2019
     */
    public String getNickName() {
        return nickName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer_info.nick_name
     *
     * @param nickName the value for customer_info.nick_name
     *
     * @mbg.generated Mon Jul 22 16:39:23 CST 2019
     */
    public void setNickName(String nickName) {
        this.nickName = nickName == null ? null : nickName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer_info.icon
     *
     * @return the value of customer_info.icon
     *
     * @mbg.generated Mon Jul 22 16:39:23 CST 2019
     */
    public String getIcon() {
        return icon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer_info.icon
     *
     * @param icon the value for customer_info.icon
     *
     * @mbg.generated Mon Jul 22 16:39:23 CST 2019
     */
    public void setIcon(String icon) {
        this.icon = icon == null ? null : icon.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer_info
     *
     * @mbg.generated Mon Jul 22 16:39:23 CST 2019
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        CustomerInfo other = (CustomerInfo) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getTelephone() == null ? other.getTelephone() == null : this.getTelephone().equals(other.getTelephone()))
            && (this.getEmail() == null ? other.getEmail() == null : this.getEmail().equals(other.getEmail()))
            && (this.getNickName() == null ? other.getNickName() == null : this.getNickName().equals(other.getNickName()))
            && (this.getIcon() == null ? other.getIcon() == null : this.getIcon().equals(other.getIcon()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer_info
     *
     * @mbg.generated Mon Jul 22 16:39:23 CST 2019
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getTelephone() == null) ? 0 : getTelephone().hashCode());
        result = prime * result + ((getEmail() == null) ? 0 : getEmail().hashCode());
        result = prime * result + ((getNickName() == null) ? 0 : getNickName().hashCode());
        result = prime * result + ((getIcon() == null) ? 0 : getIcon().hashCode());
        return result;
    }
}