package com.javaee.hotel.domain;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class HotelExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table hotel
     *
     * @mbg.generated Thu Jul 25 10:27:42 CST 2019
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table hotel
     *
     * @mbg.generated Thu Jul 25 10:27:42 CST 2019
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table hotel
     *
     * @mbg.generated Thu Jul 25 10:27:42 CST 2019
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hotel
     *
     * @mbg.generated Thu Jul 25 10:27:42 CST 2019
     */
    public HotelExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hotel
     *
     * @mbg.generated Thu Jul 25 10:27:42 CST 2019
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hotel
     *
     * @mbg.generated Thu Jul 25 10:27:42 CST 2019
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hotel
     *
     * @mbg.generated Thu Jul 25 10:27:42 CST 2019
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hotel
     *
     * @mbg.generated Thu Jul 25 10:27:42 CST 2019
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hotel
     *
     * @mbg.generated Thu Jul 25 10:27:42 CST 2019
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hotel
     *
     * @mbg.generated Thu Jul 25 10:27:42 CST 2019
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hotel
     *
     * @mbg.generated Thu Jul 25 10:27:42 CST 2019
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hotel
     *
     * @mbg.generated Thu Jul 25 10:27:42 CST 2019
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hotel
     *
     * @mbg.generated Thu Jul 25 10:27:42 CST 2019
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hotel
     *
     * @mbg.generated Thu Jul 25 10:27:42 CST 2019
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table hotel
     *
     * @mbg.generated Thu Jul 25 10:27:42 CST 2019
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andHotelIdIsNull() {
            addCriterion("hotel_id is null");
            return (Criteria) this;
        }

        public Criteria andHotelIdIsNotNull() {
            addCriterion("hotel_id is not null");
            return (Criteria) this;
        }

        public Criteria andHotelIdEqualTo(String value) {
            addCriterion("hotel_id =", value, "hotelId");
            return (Criteria) this;
        }

        public Criteria andHotelIdNotEqualTo(String value) {
            addCriterion("hotel_id <>", value, "hotelId");
            return (Criteria) this;
        }

        public Criteria andHotelIdGreaterThan(String value) {
            addCriterion("hotel_id >", value, "hotelId");
            return (Criteria) this;
        }

        public Criteria andHotelIdGreaterThanOrEqualTo(String value) {
            addCriterion("hotel_id >=", value, "hotelId");
            return (Criteria) this;
        }

        public Criteria andHotelIdLessThan(String value) {
            addCriterion("hotel_id <", value, "hotelId");
            return (Criteria) this;
        }

        public Criteria andHotelIdLessThanOrEqualTo(String value) {
            addCriterion("hotel_id <=", value, "hotelId");
            return (Criteria) this;
        }

        public Criteria andHotelIdLike(String value) {
            addCriterion("hotel_id like", value, "hotelId");
            return (Criteria) this;
        }

        public Criteria andHotelIdNotLike(String value) {
            addCriterion("hotel_id not like", value, "hotelId");
            return (Criteria) this;
        }

        public Criteria andHotelIdIn(List<String> values) {
            addCriterion("hotel_id in", values, "hotelId");
            return (Criteria) this;
        }

        public Criteria andHotelIdNotIn(List<String> values) {
            addCriterion("hotel_id not in", values, "hotelId");
            return (Criteria) this;
        }

        public Criteria andHotelIdBetween(String value1, String value2) {
            addCriterion("hotel_id between", value1, value2, "hotelId");
            return (Criteria) this;
        }

        public Criteria andHotelIdNotBetween(String value1, String value2) {
            addCriterion("hotel_id not between", value1, value2, "hotelId");
            return (Criteria) this;
        }

        public Criteria andHotelChineseNameIsNull() {
            addCriterion("hotel_chinese_name is null");
            return (Criteria) this;
        }

        public Criteria andHotelChineseNameIsNotNull() {
            addCriterion("hotel_chinese_name is not null");
            return (Criteria) this;
        }

        public Criteria andHotelChineseNameEqualTo(String value) {
            addCriterion("hotel_chinese_name =", value, "hotelChineseName");
            return (Criteria) this;
        }

        public Criteria andHotelChineseNameNotEqualTo(String value) {
            addCriterion("hotel_chinese_name <>", value, "hotelChineseName");
            return (Criteria) this;
        }

        public Criteria andHotelChineseNameGreaterThan(String value) {
            addCriterion("hotel_chinese_name >", value, "hotelChineseName");
            return (Criteria) this;
        }

        public Criteria andHotelChineseNameGreaterThanOrEqualTo(String value) {
            addCriterion("hotel_chinese_name >=", value, "hotelChineseName");
            return (Criteria) this;
        }

        public Criteria andHotelChineseNameLessThan(String value) {
            addCriterion("hotel_chinese_name <", value, "hotelChineseName");
            return (Criteria) this;
        }

        public Criteria andHotelChineseNameLessThanOrEqualTo(String value) {
            addCriterion("hotel_chinese_name <=", value, "hotelChineseName");
            return (Criteria) this;
        }

        public Criteria andHotelChineseNameLike(String value) {
            addCriterion("hotel_chinese_name like", value, "hotelChineseName");
            return (Criteria) this;
        }

        public Criteria andHotelChineseNameNotLike(String value) {
            addCriterion("hotel_chinese_name not like", value, "hotelChineseName");
            return (Criteria) this;
        }

        public Criteria andHotelChineseNameIn(List<String> values) {
            addCriterion("hotel_chinese_name in", values, "hotelChineseName");
            return (Criteria) this;
        }

        public Criteria andHotelChineseNameNotIn(List<String> values) {
            addCriterion("hotel_chinese_name not in", values, "hotelChineseName");
            return (Criteria) this;
        }

        public Criteria andHotelChineseNameBetween(String value1, String value2) {
            addCriterion("hotel_chinese_name between", value1, value2, "hotelChineseName");
            return (Criteria) this;
        }

        public Criteria andHotelChineseNameNotBetween(String value1, String value2) {
            addCriterion("hotel_chinese_name not between", value1, value2, "hotelChineseName");
            return (Criteria) this;
        }

        public Criteria andHotelAddressIsNull() {
            addCriterion("hotel_address is null");
            return (Criteria) this;
        }

        public Criteria andHotelAddressIsNotNull() {
            addCriterion("hotel_address is not null");
            return (Criteria) this;
        }

        public Criteria andHotelAddressEqualTo(String value) {
            addCriterion("hotel_address =", value, "hotelAddress");
            return (Criteria) this;
        }

        public Criteria andHotelAddressNotEqualTo(String value) {
            addCriterion("hotel_address <>", value, "hotelAddress");
            return (Criteria) this;
        }

        public Criteria andHotelAddressGreaterThan(String value) {
            addCriterion("hotel_address >", value, "hotelAddress");
            return (Criteria) this;
        }

        public Criteria andHotelAddressGreaterThanOrEqualTo(String value) {
            addCriterion("hotel_address >=", value, "hotelAddress");
            return (Criteria) this;
        }

        public Criteria andHotelAddressLessThan(String value) {
            addCriterion("hotel_address <", value, "hotelAddress");
            return (Criteria) this;
        }

        public Criteria andHotelAddressLessThanOrEqualTo(String value) {
            addCriterion("hotel_address <=", value, "hotelAddress");
            return (Criteria) this;
        }

        public Criteria andHotelAddressLike(String value) {
            addCriterion("hotel_address like", value, "hotelAddress");
            return (Criteria) this;
        }

        public Criteria andHotelAddressNotLike(String value) {
            addCriterion("hotel_address not like", value, "hotelAddress");
            return (Criteria) this;
        }

        public Criteria andHotelAddressIn(List<String> values) {
            addCriterion("hotel_address in", values, "hotelAddress");
            return (Criteria) this;
        }

        public Criteria andHotelAddressNotIn(List<String> values) {
            addCriterion("hotel_address not in", values, "hotelAddress");
            return (Criteria) this;
        }

        public Criteria andHotelAddressBetween(String value1, String value2) {
            addCriterion("hotel_address between", value1, value2, "hotelAddress");
            return (Criteria) this;
        }

        public Criteria andHotelAddressNotBetween(String value1, String value2) {
            addCriterion("hotel_address not between", value1, value2, "hotelAddress");
            return (Criteria) this;
        }

        public Criteria andHotelStarsIsNull() {
            addCriterion("hotel_stars is null");
            return (Criteria) this;
        }

        public Criteria andHotelStarsIsNotNull() {
            addCriterion("hotel_stars is not null");
            return (Criteria) this;
        }

        public Criteria andHotelStarsEqualTo(Integer value) {
            addCriterion("hotel_stars =", value, "hotelStars");
            return (Criteria) this;
        }

        public Criteria andHotelStarsNotEqualTo(Integer value) {
            addCriterion("hotel_stars <>", value, "hotelStars");
            return (Criteria) this;
        }

        public Criteria andHotelStarsGreaterThan(Integer value) {
            addCriterion("hotel_stars >", value, "hotelStars");
            return (Criteria) this;
        }

        public Criteria andHotelStarsGreaterThanOrEqualTo(Integer value) {
            addCriterion("hotel_stars >=", value, "hotelStars");
            return (Criteria) this;
        }

        public Criteria andHotelStarsLessThan(Integer value) {
            addCriterion("hotel_stars <", value, "hotelStars");
            return (Criteria) this;
        }

        public Criteria andHotelStarsLessThanOrEqualTo(Integer value) {
            addCriterion("hotel_stars <=", value, "hotelStars");
            return (Criteria) this;
        }

        public Criteria andHotelStarsIn(List<Integer> values) {
            addCriterion("hotel_stars in", values, "hotelStars");
            return (Criteria) this;
        }

        public Criteria andHotelStarsNotIn(List<Integer> values) {
            addCriterion("hotel_stars not in", values, "hotelStars");
            return (Criteria) this;
        }

        public Criteria andHotelStarsBetween(Integer value1, Integer value2) {
            addCriterion("hotel_stars between", value1, value2, "hotelStars");
            return (Criteria) this;
        }

        public Criteria andHotelStarsNotBetween(Integer value1, Integer value2) {
            addCriterion("hotel_stars not between", value1, value2, "hotelStars");
            return (Criteria) this;
        }

        public Criteria andHotelLongitudeIsNull() {
            addCriterion("hotel_longitude is null");
            return (Criteria) this;
        }

        public Criteria andHotelLongitudeIsNotNull() {
            addCriterion("hotel_longitude is not null");
            return (Criteria) this;
        }

        public Criteria andHotelLongitudeEqualTo(Float value) {
            addCriterion("hotel_longitude =", value, "hotelLongitude");
            return (Criteria) this;
        }

        public Criteria andHotelLongitudeNotEqualTo(Float value) {
            addCriterion("hotel_longitude <>", value, "hotelLongitude");
            return (Criteria) this;
        }

        public Criteria andHotelLongitudeGreaterThan(Float value) {
            addCriterion("hotel_longitude >", value, "hotelLongitude");
            return (Criteria) this;
        }

        public Criteria andHotelLongitudeGreaterThanOrEqualTo(Float value) {
            addCriterion("hotel_longitude >=", value, "hotelLongitude");
            return (Criteria) this;
        }

        public Criteria andHotelLongitudeLessThan(Float value) {
            addCriterion("hotel_longitude <", value, "hotelLongitude");
            return (Criteria) this;
        }

        public Criteria andHotelLongitudeLessThanOrEqualTo(Float value) {
            addCriterion("hotel_longitude <=", value, "hotelLongitude");
            return (Criteria) this;
        }

        public Criteria andHotelLongitudeIn(List<Float> values) {
            addCriterion("hotel_longitude in", values, "hotelLongitude");
            return (Criteria) this;
        }

        public Criteria andHotelLongitudeNotIn(List<Float> values) {
            addCriterion("hotel_longitude not in", values, "hotelLongitude");
            return (Criteria) this;
        }

        public Criteria andHotelLongitudeBetween(Float value1, Float value2) {
            addCriterion("hotel_longitude between", value1, value2, "hotelLongitude");
            return (Criteria) this;
        }

        public Criteria andHotelLongitudeNotBetween(Float value1, Float value2) {
            addCriterion("hotel_longitude not between", value1, value2, "hotelLongitude");
            return (Criteria) this;
        }

        public Criteria andHotelLatitudeIsNull() {
            addCriterion("hotel_latitude is null");
            return (Criteria) this;
        }

        public Criteria andHotelLatitudeIsNotNull() {
            addCriterion("hotel_latitude is not null");
            return (Criteria) this;
        }

        public Criteria andHotelLatitudeEqualTo(Float value) {
            addCriterion("hotel_latitude =", value, "hotelLatitude");
            return (Criteria) this;
        }

        public Criteria andHotelLatitudeNotEqualTo(Float value) {
            addCriterion("hotel_latitude <>", value, "hotelLatitude");
            return (Criteria) this;
        }

        public Criteria andHotelLatitudeGreaterThan(Float value) {
            addCriterion("hotel_latitude >", value, "hotelLatitude");
            return (Criteria) this;
        }

        public Criteria andHotelLatitudeGreaterThanOrEqualTo(Float value) {
            addCriterion("hotel_latitude >=", value, "hotelLatitude");
            return (Criteria) this;
        }

        public Criteria andHotelLatitudeLessThan(Float value) {
            addCriterion("hotel_latitude <", value, "hotelLatitude");
            return (Criteria) this;
        }

        public Criteria andHotelLatitudeLessThanOrEqualTo(Float value) {
            addCriterion("hotel_latitude <=", value, "hotelLatitude");
            return (Criteria) this;
        }

        public Criteria andHotelLatitudeIn(List<Float> values) {
            addCriterion("hotel_latitude in", values, "hotelLatitude");
            return (Criteria) this;
        }

        public Criteria andHotelLatitudeNotIn(List<Float> values) {
            addCriterion("hotel_latitude not in", values, "hotelLatitude");
            return (Criteria) this;
        }

        public Criteria andHotelLatitudeBetween(Float value1, Float value2) {
            addCriterion("hotel_latitude between", value1, value2, "hotelLatitude");
            return (Criteria) this;
        }

        public Criteria andHotelLatitudeNotBetween(Float value1, Float value2) {
            addCriterion("hotel_latitude not between", value1, value2, "hotelLatitude");
            return (Criteria) this;
        }

        public Criteria andHotelProfileIsNull() {
            addCriterion("hotel_profile is null");
            return (Criteria) this;
        }

        public Criteria andHotelProfileIsNotNull() {
            addCriterion("hotel_profile is not null");
            return (Criteria) this;
        }

        public Criteria andHotelProfileEqualTo(String value) {
            addCriterion("hotel_profile =", value, "hotelProfile");
            return (Criteria) this;
        }

        public Criteria andHotelProfileNotEqualTo(String value) {
            addCriterion("hotel_profile <>", value, "hotelProfile");
            return (Criteria) this;
        }

        public Criteria andHotelProfileGreaterThan(String value) {
            addCriterion("hotel_profile >", value, "hotelProfile");
            return (Criteria) this;
        }

        public Criteria andHotelProfileGreaterThanOrEqualTo(String value) {
            addCriterion("hotel_profile >=", value, "hotelProfile");
            return (Criteria) this;
        }

        public Criteria andHotelProfileLessThan(String value) {
            addCriterion("hotel_profile <", value, "hotelProfile");
            return (Criteria) this;
        }

        public Criteria andHotelProfileLessThanOrEqualTo(String value) {
            addCriterion("hotel_profile <=", value, "hotelProfile");
            return (Criteria) this;
        }

        public Criteria andHotelProfileLike(String value) {
            addCriterion("hotel_profile like", value, "hotelProfile");
            return (Criteria) this;
        }

        public Criteria andHotelProfileNotLike(String value) {
            addCriterion("hotel_profile not like", value, "hotelProfile");
            return (Criteria) this;
        }

        public Criteria andHotelProfileIn(List<String> values) {
            addCriterion("hotel_profile in", values, "hotelProfile");
            return (Criteria) this;
        }

        public Criteria andHotelProfileNotIn(List<String> values) {
            addCriterion("hotel_profile not in", values, "hotelProfile");
            return (Criteria) this;
        }

        public Criteria andHotelProfileBetween(String value1, String value2) {
            addCriterion("hotel_profile between", value1, value2, "hotelProfile");
            return (Criteria) this;
        }

        public Criteria andHotelProfileNotBetween(String value1, String value2) {
            addCriterion("hotel_profile not between", value1, value2, "hotelProfile");
            return (Criteria) this;
        }

        public Criteria andHotelRatingIsNull() {
            addCriterion("hotel_rating is null");
            return (Criteria) this;
        }

        public Criteria andHotelRatingIsNotNull() {
            addCriterion("hotel_rating is not null");
            return (Criteria) this;
        }

        public Criteria andHotelRatingEqualTo(Float value) {
            addCriterion("hotel_rating =", value, "hotelRating");
            return (Criteria) this;
        }

        public Criteria andHotelRatingNotEqualTo(Float value) {
            addCriterion("hotel_rating <>", value, "hotelRating");
            return (Criteria) this;
        }

        public Criteria andHotelRatingGreaterThan(Float value) {
            addCriterion("hotel_rating >", value, "hotelRating");
            return (Criteria) this;
        }

        public Criteria andHotelRatingGreaterThanOrEqualTo(Float value) {
            addCriterion("hotel_rating >=", value, "hotelRating");
            return (Criteria) this;
        }

        public Criteria andHotelRatingLessThan(Float value) {
            addCriterion("hotel_rating <", value, "hotelRating");
            return (Criteria) this;
        }

        public Criteria andHotelRatingLessThanOrEqualTo(Float value) {
            addCriterion("hotel_rating <=", value, "hotelRating");
            return (Criteria) this;
        }

        public Criteria andHotelRatingIn(List<Float> values) {
            addCriterion("hotel_rating in", values, "hotelRating");
            return (Criteria) this;
        }

        public Criteria andHotelRatingNotIn(List<Float> values) {
            addCriterion("hotel_rating not in", values, "hotelRating");
            return (Criteria) this;
        }

        public Criteria andHotelRatingBetween(Float value1, Float value2) {
            addCriterion("hotel_rating between", value1, value2, "hotelRating");
            return (Criteria) this;
        }

        public Criteria andHotelRatingNotBetween(Float value1, Float value2) {
            addCriterion("hotel_rating not between", value1, value2, "hotelRating");
            return (Criteria) this;
        }

        public Criteria andMinHotelPriceIsNull() {
            addCriterion("min_hotel_price is null");
            return (Criteria) this;
        }

        public Criteria andMinHotelPriceIsNotNull() {
            addCriterion("min_hotel_price is not null");
            return (Criteria) this;
        }

        public Criteria andMinHotelPriceEqualTo(Float value) {
            addCriterion("min_hotel_price =", value, "minHotelPrice");
            return (Criteria) this;
        }

        public Criteria andMinHotelPriceNotEqualTo(Float value) {
            addCriterion("min_hotel_price <>", value, "minHotelPrice");
            return (Criteria) this;
        }

        public Criteria andMinHotelPriceGreaterThan(Float value) {
            addCriterion("min_hotel_price >", value, "minHotelPrice");
            return (Criteria) this;
        }

        public Criteria andMinHotelPriceGreaterThanOrEqualTo(Float value) {
            addCriterion("min_hotel_price >=", value, "minHotelPrice");
            return (Criteria) this;
        }

        public Criteria andMinHotelPriceLessThan(Float value) {
            addCriterion("min_hotel_price <", value, "minHotelPrice");
            return (Criteria) this;
        }

        public Criteria andMinHotelPriceLessThanOrEqualTo(Float value) {
            addCriterion("min_hotel_price <=", value, "minHotelPrice");
            return (Criteria) this;
        }

        public Criteria andMinHotelPriceIn(List<Float> values) {
            addCriterion("min_hotel_price in", values, "minHotelPrice");
            return (Criteria) this;
        }

        public Criteria andMinHotelPriceNotIn(List<Float> values) {
            addCriterion("min_hotel_price not in", values, "minHotelPrice");
            return (Criteria) this;
        }

        public Criteria andMinHotelPriceBetween(Float value1, Float value2) {
            addCriterion("min_hotel_price between", value1, value2, "minHotelPrice");
            return (Criteria) this;
        }

        public Criteria andMinHotelPriceNotBetween(Float value1, Float value2) {
            addCriterion("min_hotel_price not between", value1, value2, "minHotelPrice");
            return (Criteria) this;
        }

        public Criteria andHotelRestRoomIsNull() {
            addCriterion("hotel_rest_room is null");
            return (Criteria) this;
        }

        public Criteria andHotelRestRoomIsNotNull() {
            addCriterion("hotel_rest_room is not null");
            return (Criteria) this;
        }

        public Criteria andHotelRestRoomEqualTo(Integer value) {
            addCriterion("hotel_rest_room =", value, "hotelRestRoom");
            return (Criteria) this;
        }

        public Criteria andHotelRestRoomNotEqualTo(Integer value) {
            addCriterion("hotel_rest_room <>", value, "hotelRestRoom");
            return (Criteria) this;
        }

        public Criteria andHotelRestRoomGreaterThan(Integer value) {
            addCriterion("hotel_rest_room >", value, "hotelRestRoom");
            return (Criteria) this;
        }

        public Criteria andHotelRestRoomGreaterThanOrEqualTo(Integer value) {
            addCriterion("hotel_rest_room >=", value, "hotelRestRoom");
            return (Criteria) this;
        }

        public Criteria andHotelRestRoomLessThan(Integer value) {
            addCriterion("hotel_rest_room <", value, "hotelRestRoom");
            return (Criteria) this;
        }

        public Criteria andHotelRestRoomLessThanOrEqualTo(Integer value) {
            addCriterion("hotel_rest_room <=", value, "hotelRestRoom");
            return (Criteria) this;
        }

        public Criteria andHotelRestRoomIn(List<Integer> values) {
            addCriterion("hotel_rest_room in", values, "hotelRestRoom");
            return (Criteria) this;
        }

        public Criteria andHotelRestRoomNotIn(List<Integer> values) {
            addCriterion("hotel_rest_room not in", values, "hotelRestRoom");
            return (Criteria) this;
        }

        public Criteria andHotelRestRoomBetween(Integer value1, Integer value2) {
            addCriterion("hotel_rest_room between", value1, value2, "hotelRestRoom");
            return (Criteria) this;
        }

        public Criteria andHotelRestRoomNotBetween(Integer value1, Integer value2) {
            addCriterion("hotel_rest_room not between", value1, value2, "hotelRestRoom");
            return (Criteria) this;
        }

        public Criteria andHotelCheckinTimeIsNull() {
            addCriterion("hotel_checkin_time is null");
            return (Criteria) this;
        }

        public Criteria andHotelCheckinTimeIsNotNull() {
            addCriterion("hotel_checkin_time is not null");
            return (Criteria) this;
        }

        public Criteria andHotelCheckinTimeEqualTo(Date value) {
            addCriterion("hotel_checkin_time =", value, "hotelCheckinTime");
            return (Criteria) this;
        }

        public Criteria andHotelCheckinTimeNotEqualTo(Date value) {
            addCriterion("hotel_checkin_time <>", value, "hotelCheckinTime");
            return (Criteria) this;
        }

        public Criteria andHotelCheckinTimeGreaterThan(Date value) {
            addCriterion("hotel_checkin_time >", value, "hotelCheckinTime");
            return (Criteria) this;
        }

        public Criteria andHotelCheckinTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("hotel_checkin_time >=", value, "hotelCheckinTime");
            return (Criteria) this;
        }

        public Criteria andHotelCheckinTimeLessThan(Date value) {
            addCriterion("hotel_checkin_time <", value, "hotelCheckinTime");
            return (Criteria) this;
        }

        public Criteria andHotelCheckinTimeLessThanOrEqualTo(Date value) {
            addCriterion("hotel_checkin_time <=", value, "hotelCheckinTime");
            return (Criteria) this;
        }

        public Criteria andHotelCheckinTimeIn(List<Date> values) {
            addCriterion("hotel_checkin_time in", values, "hotelCheckinTime");
            return (Criteria) this;
        }

        public Criteria andHotelCheckinTimeNotIn(List<Date> values) {
            addCriterion("hotel_checkin_time not in", values, "hotelCheckinTime");
            return (Criteria) this;
        }

        public Criteria andHotelCheckinTimeBetween(Date value1, Date value2) {
            addCriterion("hotel_checkin_time between", value1, value2, "hotelCheckinTime");
            return (Criteria) this;
        }

        public Criteria andHotelCheckinTimeNotBetween(Date value1, Date value2) {
            addCriterion("hotel_checkin_time not between", value1, value2, "hotelCheckinTime");
            return (Criteria) this;
        }

        public Criteria andHotelCheckoutTimeIsNull() {
            addCriterion("hotel_checkout_time is null");
            return (Criteria) this;
        }

        public Criteria andHotelCheckoutTimeIsNotNull() {
            addCriterion("hotel_checkout_time is not null");
            return (Criteria) this;
        }

        public Criteria andHotelCheckoutTimeEqualTo(Date value) {
            addCriterion("hotel_checkout_time =", value, "hotelCheckoutTime");
            return (Criteria) this;
        }

        public Criteria andHotelCheckoutTimeNotEqualTo(Date value) {
            addCriterion("hotel_checkout_time <>", value, "hotelCheckoutTime");
            return (Criteria) this;
        }

        public Criteria andHotelCheckoutTimeGreaterThan(Date value) {
            addCriterion("hotel_checkout_time >", value, "hotelCheckoutTime");
            return (Criteria) this;
        }

        public Criteria andHotelCheckoutTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("hotel_checkout_time >=", value, "hotelCheckoutTime");
            return (Criteria) this;
        }

        public Criteria andHotelCheckoutTimeLessThan(Date value) {
            addCriterion("hotel_checkout_time <", value, "hotelCheckoutTime");
            return (Criteria) this;
        }

        public Criteria andHotelCheckoutTimeLessThanOrEqualTo(Date value) {
            addCriterion("hotel_checkout_time <=", value, "hotelCheckoutTime");
            return (Criteria) this;
        }

        public Criteria andHotelCheckoutTimeIn(List<Date> values) {
            addCriterion("hotel_checkout_time in", values, "hotelCheckoutTime");
            return (Criteria) this;
        }

        public Criteria andHotelCheckoutTimeNotIn(List<Date> values) {
            addCriterion("hotel_checkout_time not in", values, "hotelCheckoutTime");
            return (Criteria) this;
        }

        public Criteria andHotelCheckoutTimeBetween(Date value1, Date value2) {
            addCriterion("hotel_checkout_time between", value1, value2, "hotelCheckoutTime");
            return (Criteria) this;
        }

        public Criteria andHotelCheckoutTimeNotBetween(Date value1, Date value2) {
            addCriterion("hotel_checkout_time not between", value1, value2, "hotelCheckoutTime");
            return (Criteria) this;
        }

        public Criteria andHotelContactIsNull() {
            addCriterion("hotel_contact is null");
            return (Criteria) this;
        }

        public Criteria andHotelContactIsNotNull() {
            addCriterion("hotel_contact is not null");
            return (Criteria) this;
        }

        public Criteria andHotelContactEqualTo(String value) {
            addCriterion("hotel_contact =", value, "hotelContact");
            return (Criteria) this;
        }

        public Criteria andHotelContactNotEqualTo(String value) {
            addCriterion("hotel_contact <>", value, "hotelContact");
            return (Criteria) this;
        }

        public Criteria andHotelContactGreaterThan(String value) {
            addCriterion("hotel_contact >", value, "hotelContact");
            return (Criteria) this;
        }

        public Criteria andHotelContactGreaterThanOrEqualTo(String value) {
            addCriterion("hotel_contact >=", value, "hotelContact");
            return (Criteria) this;
        }

        public Criteria andHotelContactLessThan(String value) {
            addCriterion("hotel_contact <", value, "hotelContact");
            return (Criteria) this;
        }

        public Criteria andHotelContactLessThanOrEqualTo(String value) {
            addCriterion("hotel_contact <=", value, "hotelContact");
            return (Criteria) this;
        }

        public Criteria andHotelContactLike(String value) {
            addCriterion("hotel_contact like", value, "hotelContact");
            return (Criteria) this;
        }

        public Criteria andHotelContactNotLike(String value) {
            addCriterion("hotel_contact not like", value, "hotelContact");
            return (Criteria) this;
        }

        public Criteria andHotelContactIn(List<String> values) {
            addCriterion("hotel_contact in", values, "hotelContact");
            return (Criteria) this;
        }

        public Criteria andHotelContactNotIn(List<String> values) {
            addCriterion("hotel_contact not in", values, "hotelContact");
            return (Criteria) this;
        }

        public Criteria andHotelContactBetween(String value1, String value2) {
            addCriterion("hotel_contact between", value1, value2, "hotelContact");
            return (Criteria) this;
        }

        public Criteria andHotelContactNotBetween(String value1, String value2) {
            addCriterion("hotel_contact not between", value1, value2, "hotelContact");
            return (Criteria) this;
        }

        public Criteria andParkingIsNull() {
            addCriterion("parking is null");
            return (Criteria) this;
        }

        public Criteria andParkingIsNotNull() {
            addCriterion("parking is not null");
            return (Criteria) this;
        }

        public Criteria andParkingEqualTo(Byte value) {
            addCriterion("parking =", value, "parking");
            return (Criteria) this;
        }

        public Criteria andParkingNotEqualTo(Byte value) {
            addCriterion("parking <>", value, "parking");
            return (Criteria) this;
        }

        public Criteria andParkingGreaterThan(Byte value) {
            addCriterion("parking >", value, "parking");
            return (Criteria) this;
        }

        public Criteria andParkingGreaterThanOrEqualTo(Byte value) {
            addCriterion("parking >=", value, "parking");
            return (Criteria) this;
        }

        public Criteria andParkingLessThan(Byte value) {
            addCriterion("parking <", value, "parking");
            return (Criteria) this;
        }

        public Criteria andParkingLessThanOrEqualTo(Byte value) {
            addCriterion("parking <=", value, "parking");
            return (Criteria) this;
        }

        public Criteria andParkingIn(List<Byte> values) {
            addCriterion("parking in", values, "parking");
            return (Criteria) this;
        }

        public Criteria andParkingNotIn(List<Byte> values) {
            addCriterion("parking not in", values, "parking");
            return (Criteria) this;
        }

        public Criteria andParkingBetween(Byte value1, Byte value2) {
            addCriterion("parking between", value1, value2, "parking");
            return (Criteria) this;
        }

        public Criteria andParkingNotBetween(Byte value1, Byte value2) {
            addCriterion("parking not between", value1, value2, "parking");
            return (Criteria) this;
        }

        public Criteria andHotalEnglishNameIsNull() {
            addCriterion("hotal_english_name is null");
            return (Criteria) this;
        }

        public Criteria andHotalEnglishNameIsNotNull() {
            addCriterion("hotal_english_name is not null");
            return (Criteria) this;
        }

        public Criteria andHotalEnglishNameEqualTo(String value) {
            addCriterion("hotal_english_name =", value, "hotalEnglishName");
            return (Criteria) this;
        }

        public Criteria andHotalEnglishNameNotEqualTo(String value) {
            addCriterion("hotal_english_name <>", value, "hotalEnglishName");
            return (Criteria) this;
        }

        public Criteria andHotalEnglishNameGreaterThan(String value) {
            addCriterion("hotal_english_name >", value, "hotalEnglishName");
            return (Criteria) this;
        }

        public Criteria andHotalEnglishNameGreaterThanOrEqualTo(String value) {
            addCriterion("hotal_english_name >=", value, "hotalEnglishName");
            return (Criteria) this;
        }

        public Criteria andHotalEnglishNameLessThan(String value) {
            addCriterion("hotal_english_name <", value, "hotalEnglishName");
            return (Criteria) this;
        }

        public Criteria andHotalEnglishNameLessThanOrEqualTo(String value) {
            addCriterion("hotal_english_name <=", value, "hotalEnglishName");
            return (Criteria) this;
        }

        public Criteria andHotalEnglishNameLike(String value) {
            addCriterion("hotal_english_name like", value, "hotalEnglishName");
            return (Criteria) this;
        }

        public Criteria andHotalEnglishNameNotLike(String value) {
            addCriterion("hotal_english_name not like", value, "hotalEnglishName");
            return (Criteria) this;
        }

        public Criteria andHotalEnglishNameIn(List<String> values) {
            addCriterion("hotal_english_name in", values, "hotalEnglishName");
            return (Criteria) this;
        }

        public Criteria andHotalEnglishNameNotIn(List<String> values) {
            addCriterion("hotal_english_name not in", values, "hotalEnglishName");
            return (Criteria) this;
        }

        public Criteria andHotalEnglishNameBetween(String value1, String value2) {
            addCriterion("hotal_english_name between", value1, value2, "hotalEnglishName");
            return (Criteria) this;
        }

        public Criteria andHotalEnglishNameNotBetween(String value1, String value2) {
            addCriterion("hotal_english_name not between", value1, value2, "hotalEnglishName");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table hotel
     *
     * @mbg.generated do_not_delete_during_merge Thu Jul 25 10:27:42 CST 2019
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table hotel
     *
     * @mbg.generated Thu Jul 25 10:27:42 CST 2019
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}