package com.javaee.hotel.domain;

import java.util.ArrayList;
import java.util.List;

public class IconExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table icon_table
     *
     * @mbg.generated Fri Aug 02 09:31:38 CST 2019
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table icon_table
     *
     * @mbg.generated Fri Aug 02 09:31:38 CST 2019
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table icon_table
     *
     * @mbg.generated Fri Aug 02 09:31:38 CST 2019
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table icon_table
     *
     * @mbg.generated Fri Aug 02 09:31:38 CST 2019
     */
    public IconExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table icon_table
     *
     * @mbg.generated Fri Aug 02 09:31:38 CST 2019
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table icon_table
     *
     * @mbg.generated Fri Aug 02 09:31:38 CST 2019
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table icon_table
     *
     * @mbg.generated Fri Aug 02 09:31:38 CST 2019
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table icon_table
     *
     * @mbg.generated Fri Aug 02 09:31:38 CST 2019
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table icon_table
     *
     * @mbg.generated Fri Aug 02 09:31:38 CST 2019
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table icon_table
     *
     * @mbg.generated Fri Aug 02 09:31:38 CST 2019
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table icon_table
     *
     * @mbg.generated Fri Aug 02 09:31:38 CST 2019
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table icon_table
     *
     * @mbg.generated Fri Aug 02 09:31:38 CST 2019
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table icon_table
     *
     * @mbg.generated Fri Aug 02 09:31:38 CST 2019
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table icon_table
     *
     * @mbg.generated Fri Aug 02 09:31:38 CST 2019
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table icon_table
     *
     * @mbg.generated Fri Aug 02 09:31:38 CST 2019
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIconIdIsNull() {
            addCriterion("icon_id is null");
            return (Criteria) this;
        }

        public Criteria andIconIdIsNotNull() {
            addCriterion("icon_id is not null");
            return (Criteria) this;
        }

        public Criteria andIconIdEqualTo(Integer value) {
            addCriterion("icon_id =", value, "iconId");
            return (Criteria) this;
        }

        public Criteria andIconIdNotEqualTo(Integer value) {
            addCriterion("icon_id <>", value, "iconId");
            return (Criteria) this;
        }

        public Criteria andIconIdGreaterThan(Integer value) {
            addCriterion("icon_id >", value, "iconId");
            return (Criteria) this;
        }

        public Criteria andIconIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("icon_id >=", value, "iconId");
            return (Criteria) this;
        }

        public Criteria andIconIdLessThan(Integer value) {
            addCriterion("icon_id <", value, "iconId");
            return (Criteria) this;
        }

        public Criteria andIconIdLessThanOrEqualTo(Integer value) {
            addCriterion("icon_id <=", value, "iconId");
            return (Criteria) this;
        }

        public Criteria andIconIdIn(List<Integer> values) {
            addCriterion("icon_id in", values, "iconId");
            return (Criteria) this;
        }

        public Criteria andIconIdNotIn(List<Integer> values) {
            addCriterion("icon_id not in", values, "iconId");
            return (Criteria) this;
        }

        public Criteria andIconIdBetween(Integer value1, Integer value2) {
            addCriterion("icon_id between", value1, value2, "iconId");
            return (Criteria) this;
        }

        public Criteria andIconIdNotBetween(Integer value1, Integer value2) {
            addCriterion("icon_id not between", value1, value2, "iconId");
            return (Criteria) this;
        }

        public Criteria andGroupTypeIsNull() {
            addCriterion("group_type is null");
            return (Criteria) this;
        }

        public Criteria andGroupTypeIsNotNull() {
            addCriterion("group_type is not null");
            return (Criteria) this;
        }

        public Criteria andGroupTypeEqualTo(String value) {
            addCriterion("group_type =", value, "groupType");
            return (Criteria) this;
        }

        public Criteria andGroupTypeNotEqualTo(String value) {
            addCriterion("group_type <>", value, "groupType");
            return (Criteria) this;
        }

        public Criteria andGroupTypeGreaterThan(String value) {
            addCriterion("group_type >", value, "groupType");
            return (Criteria) this;
        }

        public Criteria andGroupTypeGreaterThanOrEqualTo(String value) {
            addCriterion("group_type >=", value, "groupType");
            return (Criteria) this;
        }

        public Criteria andGroupTypeLessThan(String value) {
            addCriterion("group_type <", value, "groupType");
            return (Criteria) this;
        }

        public Criteria andGroupTypeLessThanOrEqualTo(String value) {
            addCriterion("group_type <=", value, "groupType");
            return (Criteria) this;
        }

        public Criteria andGroupTypeLike(String value) {
            addCriterion("group_type like", value, "groupType");
            return (Criteria) this;
        }

        public Criteria andGroupTypeNotLike(String value) {
            addCriterion("group_type not like", value, "groupType");
            return (Criteria) this;
        }

        public Criteria andGroupTypeIn(List<String> values) {
            addCriterion("group_type in", values, "groupType");
            return (Criteria) this;
        }

        public Criteria andGroupTypeNotIn(List<String> values) {
            addCriterion("group_type not in", values, "groupType");
            return (Criteria) this;
        }

        public Criteria andGroupTypeBetween(String value1, String value2) {
            addCriterion("group_type between", value1, value2, "groupType");
            return (Criteria) this;
        }

        public Criteria andGroupTypeNotBetween(String value1, String value2) {
            addCriterion("group_type not between", value1, value2, "groupType");
            return (Criteria) this;
        }

        public Criteria andIconClassIsNull() {
            addCriterion("icon_class is null");
            return (Criteria) this;
        }

        public Criteria andIconClassIsNotNull() {
            addCriterion("icon_class is not null");
            return (Criteria) this;
        }

        public Criteria andIconClassEqualTo(String value) {
            addCriterion("icon_class =", value, "iconClass");
            return (Criteria) this;
        }

        public Criteria andIconClassNotEqualTo(String value) {
            addCriterion("icon_class <>", value, "iconClass");
            return (Criteria) this;
        }

        public Criteria andIconClassGreaterThan(String value) {
            addCriterion("icon_class >", value, "iconClass");
            return (Criteria) this;
        }

        public Criteria andIconClassGreaterThanOrEqualTo(String value) {
            addCriterion("icon_class >=", value, "iconClass");
            return (Criteria) this;
        }

        public Criteria andIconClassLessThan(String value) {
            addCriterion("icon_class <", value, "iconClass");
            return (Criteria) this;
        }

        public Criteria andIconClassLessThanOrEqualTo(String value) {
            addCriterion("icon_class <=", value, "iconClass");
            return (Criteria) this;
        }

        public Criteria andIconClassLike(String value) {
            addCriterion("icon_class like", value, "iconClass");
            return (Criteria) this;
        }

        public Criteria andIconClassNotLike(String value) {
            addCriterion("icon_class not like", value, "iconClass");
            return (Criteria) this;
        }

        public Criteria andIconClassIn(List<String> values) {
            addCriterion("icon_class in", values, "iconClass");
            return (Criteria) this;
        }

        public Criteria andIconClassNotIn(List<String> values) {
            addCriterion("icon_class not in", values, "iconClass");
            return (Criteria) this;
        }

        public Criteria andIconClassBetween(String value1, String value2) {
            addCriterion("icon_class between", value1, value2, "iconClass");
            return (Criteria) this;
        }

        public Criteria andIconClassNotBetween(String value1, String value2) {
            addCriterion("icon_class not between", value1, value2, "iconClass");
            return (Criteria) this;
        }

        public Criteria andIconTextIsNull() {
            addCriterion("icon_text is null");
            return (Criteria) this;
        }

        public Criteria andIconTextIsNotNull() {
            addCriterion("icon_text is not null");
            return (Criteria) this;
        }

        public Criteria andIconTextEqualTo(String value) {
            addCriterion("icon_text =", value, "iconText");
            return (Criteria) this;
        }

        public Criteria andIconTextNotEqualTo(String value) {
            addCriterion("icon_text <>", value, "iconText");
            return (Criteria) this;
        }

        public Criteria andIconTextGreaterThan(String value) {
            addCriterion("icon_text >", value, "iconText");
            return (Criteria) this;
        }

        public Criteria andIconTextGreaterThanOrEqualTo(String value) {
            addCriterion("icon_text >=", value, "iconText");
            return (Criteria) this;
        }

        public Criteria andIconTextLessThan(String value) {
            addCriterion("icon_text <", value, "iconText");
            return (Criteria) this;
        }

        public Criteria andIconTextLessThanOrEqualTo(String value) {
            addCriterion("icon_text <=", value, "iconText");
            return (Criteria) this;
        }

        public Criteria andIconTextLike(String value) {
            addCriterion("icon_text like", value, "iconText");
            return (Criteria) this;
        }

        public Criteria andIconTextNotLike(String value) {
            addCriterion("icon_text not like", value, "iconText");
            return (Criteria) this;
        }

        public Criteria andIconTextIn(List<String> values) {
            addCriterion("icon_text in", values, "iconText");
            return (Criteria) this;
        }

        public Criteria andIconTextNotIn(List<String> values) {
            addCriterion("icon_text not in", values, "iconText");
            return (Criteria) this;
        }

        public Criteria andIconTextBetween(String value1, String value2) {
            addCriterion("icon_text between", value1, value2, "iconText");
            return (Criteria) this;
        }

        public Criteria andIconTextNotBetween(String value1, String value2) {
            addCriterion("icon_text not between", value1, value2, "iconText");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table icon_table
     *
     * @mbg.generated do_not_delete_during_merge Fri Aug 02 09:31:38 CST 2019
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table icon_table
     *
     * @mbg.generated Fri Aug 02 09:31:38 CST 2019
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}