package com.javaee.hotel.domain;

import java.util.Date;

public class PriceChange {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column price_change.price_change_id
     *
     * @mbg.generated Wed Aug 07 12:02:10 CST 2019
     */
    private String priceChangeId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column price_change.room_id
     *
     * @mbg.generated Wed Aug 07 12:02:10 CST 2019
     */
    private String roomId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column price_change.price
     *
     * @mbg.generated Wed Aug 07 12:02:10 CST 2019
     */
    private Float price;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column price_change.date_start
     *
     * @mbg.generated Wed Aug 07 12:02:10 CST 2019
     */
    private Date dateStart;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column price_change.date_end
     *
     * @mbg.generated Wed Aug 07 12:02:10 CST 2019
     */
    private Date dateEnd;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column price_change.price_change_id
     *
     * @return the value of price_change.price_change_id
     *
     * @mbg.generated Wed Aug 07 12:02:10 CST 2019
     */
    public String getPriceChangeId() {
        return priceChangeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column price_change.price_change_id
     *
     * @param priceChangeId the value for price_change.price_change_id
     *
     * @mbg.generated Wed Aug 07 12:02:10 CST 2019
     */
    public void setPriceChangeId(String priceChangeId) {
        this.priceChangeId = priceChangeId == null ? null : priceChangeId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column price_change.room_id
     *
     * @return the value of price_change.room_id
     *
     * @mbg.generated Wed Aug 07 12:02:10 CST 2019
     */
    public String getRoomId() {
        return roomId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column price_change.room_id
     *
     * @param roomId the value for price_change.room_id
     *
     * @mbg.generated Wed Aug 07 12:02:10 CST 2019
     */
    public void setRoomId(String roomId) {
        this.roomId = roomId == null ? null : roomId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column price_change.price
     *
     * @return the value of price_change.price
     *
     * @mbg.generated Wed Aug 07 12:02:10 CST 2019
     */
    public Float getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column price_change.price
     *
     * @param price the value for price_change.price
     *
     * @mbg.generated Wed Aug 07 12:02:10 CST 2019
     */
    public void setPrice(Float price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column price_change.date_start
     *
     * @return the value of price_change.date_start
     *
     * @mbg.generated Wed Aug 07 12:02:10 CST 2019
     */
    public Date getDateStart() {
        return dateStart;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column price_change.date_start
     *
     * @param dateStart the value for price_change.date_start
     *
     * @mbg.generated Wed Aug 07 12:02:10 CST 2019
     */
    public void setDateStart(Date dateStart) {
        this.dateStart = dateStart;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column price_change.date_end
     *
     * @return the value of price_change.date_end
     *
     * @mbg.generated Wed Aug 07 12:02:10 CST 2019
     */
    public Date getDateEnd() {
        return dateEnd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column price_change.date_end
     *
     * @param dateEnd the value for price_change.date_end
     *
     * @mbg.generated Wed Aug 07 12:02:10 CST 2019
     */
    public void setDateEnd(Date dateEnd) {
        this.dateEnd = dateEnd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table price_change
     *
     * @mbg.generated Wed Aug 07 12:02:10 CST 2019
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        PriceChange other = (PriceChange) that;
        return (this.getPriceChangeId() == null ? other.getPriceChangeId() == null : this.getPriceChangeId().equals(other.getPriceChangeId()))
            && (this.getRoomId() == null ? other.getRoomId() == null : this.getRoomId().equals(other.getRoomId()))
            && (this.getPrice() == null ? other.getPrice() == null : this.getPrice().equals(other.getPrice()))
            && (this.getDateStart() == null ? other.getDateStart() == null : this.getDateStart().equals(other.getDateStart()))
            && (this.getDateEnd() == null ? other.getDateEnd() == null : this.getDateEnd().equals(other.getDateEnd()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table price_change
     *
     * @mbg.generated Wed Aug 07 12:02:10 CST 2019
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getPriceChangeId() == null) ? 0 : getPriceChangeId().hashCode());
        result = prime * result + ((getRoomId() == null) ? 0 : getRoomId().hashCode());
        result = prime * result + ((getPrice() == null) ? 0 : getPrice().hashCode());
        result = prime * result + ((getDateStart() == null) ? 0 : getDateStart().hashCode());
        result = prime * result + ((getDateEnd() == null) ? 0 : getDateEnd().hashCode());
        return result;
    }
}