package com.javaee.hotel.mapper;

import com.javaee.hotel.domain.OrderList;
import com.javaee.hotel.domain.OrderListExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface OrderListMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_list
     *
     * @mbg.generated Fri Aug 02 17:05:50 CST 2019
     */
    long countByExample(OrderListExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_list
     *
     * @mbg.generated Fri Aug 02 17:05:50 CST 2019
     */
    int deleteByExample(OrderListExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_list
     *
     * @mbg.generated Fri Aug 02 17:05:50 CST 2019
     */
    int deleteByPrimaryKey(String orderId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_list
     *
     * @mbg.generated Fri Aug 02 17:05:50 CST 2019
     */
    int insert(OrderList record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_list
     *
     * @mbg.generated Fri Aug 02 17:05:50 CST 2019
     */
    int insertSelective(OrderList record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_list
     *
     * @mbg.generated Fri Aug 02 17:05:50 CST 2019
     */
    List<OrderList> selectByExample(OrderListExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_list
     *
     * @mbg.generated Fri Aug 02 17:05:50 CST 2019
     */
    OrderList selectByPrimaryKey(String orderId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_list
     *
     * @mbg.generated Fri Aug 02 17:05:50 CST 2019
     */
    int updateByExampleSelective(@Param("record") OrderList record, @Param("example") OrderListExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_list
     *
     * @mbg.generated Fri Aug 02 17:05:50 CST 2019
     */
    int updateByExample(@Param("record") OrderList record, @Param("example") OrderListExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_list
     *
     * @mbg.generated Fri Aug 02 17:05:50 CST 2019
     */
    int updateByPrimaryKeySelective(OrderList record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_list
     *
     * @mbg.generated Fri Aug 02 17:05:50 CST 2019
     */
    int updateByPrimaryKey(OrderList record);
}